KGERP/Controllers/CompanyController.cs
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class CompanyController : Controller
    {
        private readonly ICompanyService companyService;
        public CompanyController(ICompanyService companyService)
        {
            this.companyService = companyService;
        }

        [SessionExpire]
        [HttpGet]
        public ActionResult Index(string searchText)
        {
            List<CompanyModel> companies = companyService.GetCompanies(searchText);
            List<CompanyModel> companiesWithImage = companies.Select(x => new CompanyModel
            {
                CompanyId = x.CompanyId,
                Name = x.Name,
                ShortName = x.ShortName,
                OrderNo = x.OrderNo,
                MushokNo = x.MushokNo,
                IsCompany = x.IsCompany,
                CompanyLogo = string.Format("{0}://{1}", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority) + "/Images/Logo/" + (string.IsNullOrEmpty(x.CompanyLogo) ? "logo.png" : x.CompanyLogo),
            }).ToList();
            return View(companiesWithImage);
        }

        [HttpGet]
        [SessionExpire]
        public ActionResult CreateOrEdit(int id)
        {
            CompanyModel company = companyService.GetCompany(id);
            company.CompanyLogo = string.Format("{0}://{1}", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority) + "/Images/Logo/" + (string.IsNullOrEmpty(company.CompanyLogo) ? "logo.png" : company.CompanyLogo);
            return View(company);
        }

        [HttpPost]
        [SessionExpire]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(CompanyModel model)
        {
            ModelState.Clear();
            string message = string.Empty;
            bool result = false;

            if (model.CompanyLogoUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(model.CompanyLogoUpload.FileName);
                string extension = Path.GetExtension(model.CompanyLogoUpload.FileName);
                fileName = fileName + "_" + DateTime.Now.ToString("yymmssfff") + extension;
                model.CompanyLogo = fileName;
                model.CompanyLogoUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Logo/"), fileName));
            }

            if (model.CompanyId <= 0)
            {
                result = companyService.SaveCompany(0, model);
            }
            else
            {
                result = companyService.SaveCompany(model.CompanyId, model);
            }
            if (result)
            {
                TempData["message"] = "Company Saved Successfully !";
            }
            else
            {
                TempData["message"] = "Company not Saved !";
            }
            return RedirectToAction("Index");
        }

    }

}

KGERP/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.EMMA;
using KGERP.Data.CustomModel;
using KGERP.Data.Models;
using KGERP.Service.Implementation;
using KGERP.Service.Implementation.Configuration;
using KGERP.Service.Implementation.FTP;
using KGERP.Service.Implementation.Procurement;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel.FTP_Models;
using KGERP.Utility;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class ConfigurationController : Controller
    {

        private HttpContext httpContext;
        private readonly ConfigurationService _service;
        private readonly ICompanyService _companyService;
        private readonly IFTPService _ftpService;
        private readonly IDepartmentService _departmentService = new DepartmentService();
        private readonly HrDesignationService _hrDesignationService = new HrDesignationService();

        public ConfigurationController(IFTPService ftpService, ICompanyService companyService, ConfigurationService configurationService)
        {
            _service = configurationService;
            _companyService = companyService;
            _ftpService = ftpService;
        }

        #region User Role Menuitem

        #region ClientUserMenuAssignment

        public ActionResult ClientUserMenuAssignment(int companyId = 0)
        {
            var dto = new ClientMenu
            {
                CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text")
            };
            return View(dto);
        }

        [HttpPost]
        public ActionResult ClientUserMenuAssignment(ClientMenu model)
        {
            if (model.CompanyId == null) return View(model);
            ClientMenu viewData = _service.ClientUserMenuAssignment(model);
            viewData.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");
            return View(viewData);

        }

        public JsonResult ClientCompanyUserMenuUpdate(int index, string userId, bool isActive, int companyId, int menuId, int subMenuId)
        {
            var result = _service.ClientCompanyUserMenuUpdate(index, userId, isActive, companyId, menuId, subMenuId);
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetUserClientMenuAssign(string prefix)
        {
            var users = _service.GetUserClientMenuAssign(prefix);
            return Json(users, JsonRequestBehavior.AllowGet);
        }

        #endregion

        // User menu assign
        public async Task<ActionResult> UserMenuAssignment(int companyId)
        {
            VMUserMenuAssignment vmUserMenuAssignment = new VMUserMenuAssignment();
            vmUserMenuAssignment.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");

            return View(vmUserMenuAssignment);
        }

        [HttpPost]
        public async Task<ActionResult> UserMenuAssignment(VMUserMenuAssignment model)
        {
            VMUserMenuAssignment vmUserMenuAssignment = new VMUserMenuAssignment();
            vmUserMenuAssignment = await _service.UserMenuAssignmentGet(model);
            return View(vmUserMenuAssignment);
        }

        public JsonResult CompanyUserMenuEdit(int id, bool isActive)
        {
            VMUserMenuAssignment model = new VMUserMenuAssignment
            {
                IsActive = isActive,
                CompanyUserMenusId = id
            };
            CompanyUserMenu companyUserMenu = _service.CompanyUserMenuEdit(model);
            return Json(new { menuid = companyUserMenu.CompanyUserMenuId, updatedstatus = companyUserMenu.IsActive });
        }

        #endregion

        public async Task<ActionResult> AccountingCostCenter(int companyId)
        {
            VMUserMenu vmUserMenu = await Task.Run(() => _service.AccountingCostCenterGet(companyId));

            return View(vmUserMenu);
        }

        [HttpPost]
        public async Task<ActionResult> AccountingCostCenter(VMUserMenu model)
        {

            if (model.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.AccountingCostCenterAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.AccountingCostCenterEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.AccountingCostCenterDelete(model.ID);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction(nameof(AccountingCostCenter), new { companyId = model.CompanyFK });
        }

        #region User Menu
        public async Task<ActionResult> UserMenu()
        {
            VMUserMenu vmUserMenu;
            vmUserMenu = await Task.Run(() => _service.UserMenuGet());
            vmUserMenu.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");

            return View(vmUserMenu);
        }

        [HttpPost]
        public async Task<ActionResult> UserMenu(VMUserMenu model)
        {

            if (model.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.UserMenuAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.UserMenuEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.UserMenuDelete(model.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(UserMenu), new { companyId = model.CompanyFK });
        }

        #endregion

        #region User Submenu
        public async Task<ActionResult> UserSubMenu()
        {
            VMUserSubMenu vmUserSubMenu;
            vmUserSubMenu = await Task.Run(() => _service.UserSubMenuGet());
            vmUserSubMenu.UserMenuList = new SelectList(_service.CompanyMenusDropDownList(), "Value", "Text");
            vmUserSubMenu.CompanyList = new SelectList(_service.CompaniesDropDownList(), "Value", "Text");

            return View(vmUserSubMenu);
        }

        [HttpPost]
        public async Task<ActionResult> UserSubMenu(VMUserSubMenu model)
        {
            if (model.ActionEum == ActionEnum.Add)
            {
                await _service.UserSubMenuAdd(model);
            }
            else if (model.ActionEum == ActionEnum.Edit)
            {
                await _service.UserSubMenuEdit(model);
            }
            else if (model.ActionEum == ActionEnum.Delete)
            {
                await _service.UserSubMenuDelete(model.ID);
            }
            else
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(UserSubMenu), new { companyId = model.CompanyFK });
        }
        #endregion

        public async Task<ActionResult> CommonUnitGet(int companyId)
        {
            var dataList = await Task.Run(() => _service.CompanyMenusGet(companyId));
            var list = dataList.Select(x => new { Value = x.ID, Text = x.Name }).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        #region Unit
        public async Task<JsonResult> SingleCommonUnit(int id)
        {

            VMCommonUnit model = new VMCommonUnit();
            model = await _service.GetSingleCommonUnit(id);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> CommonUnit(int companyId)
        {
            VMCommonUnit vmCommonUnit = new VMCommonUnit();
            vmCommonUnit = await Task.Run(() => _service.GetUnit(companyId));
            vmCommonUnit.UserDataAccessModel = await _service.GetUserDataAccessModelByEmployeeId();

            return View(vmCommonUnit);
        }

        [HttpPost]
        public async Task<ActionResult> CommonUnit(VMCommonUnit vmCommonUnit)
        {

            if (vmCommonUnit.ActionEum == ActionEnum.Add)
            {
                //Add 
                await _service.UnitAdd(vmCommonUnit);
            }
            else if (vmCommonUnit.ActionEum == ActionEnum.Edit)
            {
                //Edit
                await _service.UnitEdit(vmCommonUnit);
            }
            else if (vmCommonUnit.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.UnitDelete(vmCommonUnit.ID);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction(nameof(CommonUnit), new { companyId = vmCommonUnit.CompanyFK });
        }

        [HttpPost]
        public async Task<ActionResult> CommonUnitDelete(VMCommonUnit vmCommonUnit)
        {

            if (vmCommonUnit.ActionEum == ActionEnum.Delete)
            {
                //Delete
                await _service.UnitDelete(vmCommonUnit.ID);
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction(nameof(CommonUnit));
        }

        [HttpPost]
        public async Task<JsonResult> IsUnitNameExist(string name, int id)
        {
            if (string.IsNullOrEmpty(name))
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            var isDuplicate = await _service.CheckDuplicateUnitName(name, id);

            return Json(isDuplicate, JsonRequestBehavior.AllowGet);
        }
        #endregion

        public async Task<JsonResult> SingleProductCategory(int id)
        {

KGERP/Views/Configuration/AccountingSignatory.cshtml
@{

    ViewData["Title"] = "Raw Materials Subcategory";
    Layout = "~/Views/Shared/_Layout.cshtml";


}
@model KGERP.Service.Implementation.Configuration.VMAccountingSignatory
<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>
<section class="content-header">
    <h1>
        Account Signatory
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active"> Signatory </li>
    </ol>
</section>
@using (Html.BeginForm("AccountingSignatory", "Configuration", FormMethod.Post, new { id = "commonAccountingSignatoryFormId", @class = "formValidator", onreset = "resetDDL();" }))
{
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="box-danger">
                        <div class="box-header">
                            <h4>Add Signatory</h4>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            @Html.HiddenFor(model => model.SignatoryId, new { id = "hidSignatoryId" })
                            @Html.HiddenFor(model => model.ActionId, new { id = "ActionId" })
                            @Html.HiddenFor(model => model.CompanyFK, new { id = "CompanyFK" })
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Company Name:</label>
                                    @Html.DropDownListFor(model => model.CompanyFK, Model.CompanyList as SelectList, "---Select Company---", new { id = "ddlCompanyId", @class = "searchingDropdown form-control", required = "required" })
                                    @Html.ValidationMessageFor(model => model.CompanyFK, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Signatory Type:</label>
                                    @Html.TextBoxFor(model => model.SignatoryType, new { id = "txtSignatoryType", @class = "form-control", @placeholder = "Signatory Type" })
                                    @Html.ValidationMessageFor(model => model.SignatoryType, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Signatory Name:</label>
                                    @Html.TextBoxFor(model => model.SignatoryName, new { id = "txtSignatoryName", @class = "form-control", @placeholder = "Signatory Name" })
                                    @Html.ValidationMessageFor(model => model.SignatoryName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Order By:</label>
                                    @Html.TextBoxFor(model => model.OrderBy, new { id = "txtOrderBy", @class = "form-control", @placeholder = "Order By" })
                                    @Html.ValidationMessageFor(model => model.OrderBy, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-5">
                                    <button type="button" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Reset</button>
                                </div>
                                <div class="col-md-7">
                                    <button type="submit" id="btnSave" class="btn btn-primary btn-block"><i class='fa fa-edit'></i> Add</button>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                        </div>
                    </div>
                </div>
                <div class="box">
                    <div class="box-danger">
                        <div class="box-header">
                            <h4>Signatory List</h4>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="table-responsive col-md-12">
                                <table id="KgErpDataTable" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>SL</th>
                                            <th>Company Name</th>
                                            <th>Signatory Type</th>
                                            <th>Signatory Name</th>
                                            <th>Order By</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    @{int sl = 0;
                                    }
                                    <tbody>
                                        @foreach (var item in Model.DataList)
                                        {

                                        <tr>
                                            <td>@(++sl)</td>
                                            <td>
                                                <input type="hidden" id="CompanyFK_@item.SignatoryId" name="CompanyFK" value="@item.CompanyFK" />
                                                @item.CompanyName
                                            </td>
                                            <td id="tdSignatoryType_@item.SignatoryId">@item.SignatoryType</td>
                                            <td id="tdSignatoryName_@item.SignatoryId">@item.SignatoryName</td>
                                            <td id="tdOrderBy_@item.SignatoryId">@item.OrderBy</td>
                                            <td>
                                                <a id="@item.SignatoryId" onclick="makeEditble(this)" class="linkPointer" title="Edit"><i class="fa fa-pencil-square-o"></i></a>
                                                <a id="@item.SignatoryId" onclick="makeDeletable(@item.SignatoryId);" class="linkPointer" data-toggle="modal" data-target="#deleteModal" title="Delete"
                                                   data-placement="top">
                                                    <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                                </a>

                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="box-footer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

}

@using (Html.BeginForm("AccountingSignatory", "Configuration", FormMethod.Post, new { id = "commonAccountingSagnatoryDeleteFormId", @class = "formValidator", onreset = "resetDDL();" }))
{
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @Html.HiddenFor(model => model.SignatoryId, new { id = "SignatoryIdDelete" })
    @Html.HiddenFor(model => model.ActionId, new { id = "ActionIdDelete" })
    @Html.HiddenFor(model => model.CompanyFK, new { id = "CompanyFKDelete" })

    <div class="modal fade" id="deleteModal" data-toggle="modal" data-backdrop="static" data-keyboard="false" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" onclick="resetForm()" class="close pull-right" data-dismiss="modal" aria-label="Close">
                        &times;
                    </button>
                    <h5 class="modal-title"><b>Signatory Delete</b></h5>
                </div>
                <div class="modal-body">
                    <div style="text-align:center">
                        <h3>Are you sure to delete?</h3>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnClose" onclick="resetForm()" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnDelete" class="deleteId btn btn-primary"><i class="glyphicon glyphicon-check"></i> Confirm</button>
                </div>
            </div>
        </div>
    </div>
}

    @section scripts {
        <script type="text/javascript">
        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();

             
        });
        function makeEditble(elem) {
            if (elem !== null) {
                var rowId = elem.id;
                $('#hidSignatoryId').val(rowId);
                $('#ActionId').val(2);
                $('#btnSave').html("<i class='fa fa-edit'></i>&nbsp;Update");
                $('#ddlCompanyId').val($('#CompanyFK_' + rowId).val()).change();
                $('#txtSignatoryType').val($('#tdSignatoryType_' + rowId).text().trim());
                $('#txtSignatoryName').val($('#tdSignatoryName_' + rowId).text().trim());
                $('#txtOrderBy').val($('#tdOrderBy_' + rowId).text().trim());

                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        }
        function makeDeletable(id) {
            if (id !== null) {
                $('#SignatoryIdDelete').val(id);
                $('#ActionIdDelete').val(3);
            }
        }
        function resetForm() {
            $('#commonAccountingSignatoryFormId')[0].reset();
            $('#btnSave').html("<i class='fa fa-edit'></i>&nbsp;Add");
        }
        </script>
    }