KGERP/Controllers/InstallmentTypeController.cs
using KGERP.Service.Implementation.Realestate;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class InstallmentTypeController : Controller
    {
        private readonly IInstallmentTypeService _Service;
        public InstallmentTypeController(IInstallmentTypeService Service)
        {
            this._Service = Service;
        }

        [SessionExpire]
        [HttpGet]
        public async  Task<ActionResult> Index(int CompanyId)
        {
            InstallmentTypeViewModel model = new InstallmentTypeViewModel() { CompanyId=CompanyId};
            model.List  =await _Service.GetAllInstallmentTypesByCompanyId(CompanyId);
            return View(model);
        }

        [HttpGet]
        [SessionExpire]
        public ActionResult Create(int CompanyId=7)
        {
            InstallmentTypeInsertModel model = new InstallmentTypeInsertModel() {
                CompanyId = CompanyId
            };
            return View(model);
        }

        [HttpPost]
        [SessionExpire]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(InstallmentTypeInsertModel model)
        {
            ModelState.Clear();
            
            bool result = false;
            model.CreatedBy = User.Identity.Name;
            model.CreatedDate=DateTime.Now;
            result = await _Service.AddInstallmentType(model);
           
            if (result)
            {
                TempData["message"] = " Saved Successfully !";
            }
            else
            {
                TempData["message"] = "Not Saved !";
            }
            return RedirectToAction("Index",new { CompanyId=model.CompanyId });
        }

        [HttpGet]
        [SessionExpire]
        public async Task< ActionResult> Edit(int id)
        {
            InstallmentTypeEditModel model = new InstallmentTypeEditModel();
            var data= await _Service.GetInstallmentTypeById(id); 
            if (data == null)
            {
                TempData["message"] = "Not found";
                return RedirectToAction(nameof(Index));
            }
            model.ModifiedDate = data.ModifiedDate;
            model.ModifiedBy = data.ModifiedBy;
            model.InstallmentTypeId = data.InstallmentTypeId;
            model.IsOneTime = data.IsOneTime;
            model.Name = data.Name;
            model.CompanyId = data.CompanyId;
            model.IntervalMonths = data.IntervalMonths;
            return View(model);
        }

        [HttpPost]
        [SessionExpire]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(InstallmentTypeEditModel model)
        {
            ModelState.Clear();

            bool result = false;
            model.ModifiedBy = User.Identity.Name;
            model.ModifiedDate = DateTime.Now;
            result = await _Service.UpdateInstallmentType(model);

            if (result)
            {
                TempData["message"] = " Updated Successfully !";
            }
            else
            {
                TempData["message"] = "Couldn't Update !";
            }
            return RedirectToAction("Index", new { CompanyId = model.CompanyId });
        }

        [HttpGet]
        [SessionExpire]
       
        public async Task<ActionResult> Delete(int id)
        {
            ModelState.Clear();

            var data =await _Service.GetInstallmentTypeById(id);
            bool result = false;
            result = await _Service.DeleteInstallmentType(id);

            if (result)
            {
                TempData["message"] = " Deleted Successfully !";
            }
            else
            {
                TempData["message"] = "Failed to delete !";
            }
            return RedirectToAction("Index",new { CompanyId=data.CompanyId});
        }


    }

}

KGERP/Views/InstallmentType/Create.cshtml
@model KGERP.Service.ServiceModel.InstallmentTypeInsertModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Create", "InstallmentType", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CreatedDate)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.CompanyId)
    

<div class="form-horizontal">
    <h4>Installment Type</h4>
    <hr style="border-color:#ff0000; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-5">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-5">
            @Html.LabelFor(model => model.IntervalMonths, htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.IntervalMonths, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                @*@Html.CheckBoxFor(model => model.IsMonthly, htmlAttributes: new { @class = "form-control mt-2" })*@
                @Html.ValidationMessageFor(model => model.IntervalMonths, "", new { @class = "text-danger" })
            </div>
        </div>
        


    </div>


    <div class="form-group">
        <div class="col-md-5">
            @Html.LabelFor(model => model.IsOneTime, htmlAttributes: new { @class = "control-label col-md-7" })
            <div class="col-md-5">
                @Html.CheckBoxFor(model => model.IsOneTime, new { @class = "form-check-input mt-2 ", @style = "margin-top: 11px;" })
                @*@Html.CheckBoxFor(model => model.IsMonthly, htmlAttributes: new { @class = "form-control mt-2" })*@
                @Html.ValidationMessageFor(model => model.IsOneTime, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class=" col-md-4">
            <a href="@Url.Action("Index")" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove-circle"></span>   Close
            </a>
            <button type="submit" class="btn btn-primary " onclick="javascript: return window.confirm('Are you sure?');" style="margin-left: 20px;"><span class="glyphicon glyphicon-floppy-disk"></span>Save</button>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
}

KGERP/Views/InstallmentType/Edit.cshtml
@model KGERP.Service.ServiceModel.InstallmentTypeEditModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Edit", "InstallmentType", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.CompanyId)
    @Html.HiddenFor(model => model.InstallmentTypeId)
    @Html.HiddenFor(model => model.ModifiedBy)
    @Html.HiddenFor(model => model.ModifiedDate)

    <div class="form-horizontal">
        <h4>Update Installment Type</h4>
        <hr style="border-color:#ff0000; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-5">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-5">
                @Html.LabelFor(model => model.IntervalMonths, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.IntervalMonths, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                    @*@Html.CheckBoxFor(model => model.IsMonthly, htmlAttributes: new { @class = "form-control mt-2" })*@
                    @Html.ValidationMessageFor(model => model.IntervalMonths, "", new { @class = "text-danger" })
                </div>
            </div>



        </div>

        <div class="form-group">
            <div class="col-md-5">
                @Html.LabelFor(model => model.IsOneTime, htmlAttributes: new { @class = "control-label col-md-7" })
                <div class="col-md-5">
                    @Html.CheckBoxFor(model => model.IsOneTime, new { @class = "form-check-input mt-2 ", @style = "margin-top: 11px;" })
                    @*@Html.CheckBoxFor(model => model.IsMonthly, htmlAttributes: new { @class = "form-control mt-2" })*@
                    @Html.ValidationMessageFor(model => model.IsOneTime, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Index", new { companyId = Model.CompanyId})" class="btn btn-danger">
                    <span class="glyphicon glyphicon-remove-circle"></span>   Close
                </a>
                <button type="submit" class="btn btn-warning " onclick="javascript: return window.confirm('Are you sure?');" style="margin-left: 20px;"><span class="glyphicon glyphicon-floppy-disk"></span>Update</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
}

KGERP/Views/InstallmentType/Index.cshtml
@model KGERP.Service.ServiceModel.InstallmentTypeViewModel 
@{
    ViewData["Title"] = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/CustomCss/search-form.css" rel="stylesheet" />


<div class="row">
    <div class="col-md-5">
        <h3><b>Installment Types</b></h3>
    </div>
    <div class="col-md-2 pull-right">
        <div class="form-group">
            <a href="@Url.Action("Create",new { CompanyId=Model.CompanyId})" class="btn btn-primary pull-right">
                <span class="glyphicon glyphicon-plus-sign"></span> Add New
            </a>
        </div>
    </div>
</div>
@{ if (TempData["message"]!=null)
    {
        <div class="row">
            <strong>@TempData["message"]</strong>
        </div>

    }

}


<div class="row">
    <hr style="border-color:#32527B; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    <table id="KgErpDataTable" class="table table-striped table-condensed">
        <tr style="background-color:#3c8dbc;color:#ffffff">
            <th>
                SL
            </th>
            <th>
                Installment Scheme
            </th>
            <th>
                One Time Payment?
            </th>
            <th>
                 Interval (Months)
            </th>
            <th class="text-center">Action</th>
        </tr>

        @foreach (var item in Model.List.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td>
                    @(item.Index + 1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Name)
                </td>

                <td>
                    @if (item.Data.IsOneTime)
                    {
                        <p>Yes</p>
                    }
                    else
                    {
                        <p>No</p>
                    }
                </td>
                <td>
                    @item.Data.IntervalMonths
                </td>

                <td class="text-center">
                    <a href="@Url.Action("Edit", new { id = item.Data.InstallmentTypeId})" title="Edit" class="btn btn-info btn-xs">
                        <i class="fa fa-edit" style="font-size:15px;" aria-hidden="true"></i>
                    </a>

                    <button type="button" onclick="Delete(@item.Data.InstallmentTypeId)" class="btn btn-danger btn-xs">

                        <i class="fa fa-trash" style="font-size:15px;" aria-hidden="true"></i>
                    </button>
                </td>
            </tr>
        }

    </table>


</div>


@section Scripts{
    <script type="text/javascript">
        function Delete(id) {
            if (window.confirm('Are you sure?')) {
                var url = "@Url.Action("Delete", new { id = "_id"})";
                url = url.replace('_id', id);
                window.location = url;
            }
        }


    </script>
}