KGERP/Controllers/LeaveApplicationController.cs
using KGERP.Data.CustomModel;
using KGERP.Data.CustomViewModel;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using KGERP.ViewModel;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class LeaveApplicationController : Controller
    {
        private readonly ILeaveApplicationService leaveApplicationService;
        private readonly ILeaveCategoryService leaveCategoryService;
        private readonly IEmployeeService employeeService;
        public LeaveApplicationController(ILeaveApplicationService leaveApplicationService, ILeaveCategoryService leaveCategoryService, IEmployeeService employeeService)
        {
            this.leaveApplicationService = leaveApplicationService;
            this.leaveCategoryService = leaveCategoryService;
            this.employeeService = employeeService;
        }
        [SessionExpire]
        [HttpGet]
        public async Task<ActionResult> Index(DateTime? fromDate, DateTime? toDate)
        {        
            if (fromDate == null)
            {
                fromDate = DateTime.Now.AddMonths(-6);
            }
            if (toDate == null)
            {
                toDate = DateTime.Now;
            }
            LeaveApplicationVm model = new LeaveApplicationVm();

            model = await leaveApplicationService.GetLeaveApplicationByEmployee(fromDate, toDate);

            model.StrFromDate = fromDate.Value.ToString("yyyy-MM-dd");
            model.StrToDate = toDate.Value.ToString("yyyy-MM-dd");

            return View(model);
        }
        [HttpPost]
        [SessionExpire]
        public async Task<ActionResult> Index(LeaveApplicationVm model)
        {
            model.FromDate = Convert.ToDateTime(model.StrFromDate);
            model.ToDate = Convert.ToDateTime(model.StrToDate);
            return RedirectToAction(nameof(Index), new { fromDate = model.FromDate, toDate = model.ToDate });
        }
        
        [SessionExpire]
        [HttpGet]
        public ActionResult CreateOrEdit(long id)
        {
            LeaveApplicationViewModel vm = new LeaveApplicationViewModel();
            vm.LeaveApplication = leaveApplicationService.GetLeaveApplication(id);
            vm.LeaveCategories = leaveCategoryService.GetLeaveCategorySelectModels();
            vm.LeaveBalance = leaveApplicationService.GetLeaveBalance();
            return View(vm);
        }


        [SessionExpire]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(LeaveApplicationViewModel vm)
        {
            string message = string.Empty;
            bool result = false;
            vm.LeaveApplication.IP = Request.UserHostAddress;
            if (vm.LeaveApplication.LeaveApplicationId <= 0)
            {
                result = leaveApplicationService.SaveLeaveApplication(0, vm.LeaveApplication, out message);
            }

            else
            {
                result = leaveApplicationService.SaveLeaveApplication(vm.LeaveApplication.LeaveApplicationId, vm.LeaveApplication, out message);
            }
            TempData["errorMessage"] = message;


            if (!result)
            {
                vm.LeaveApplication = leaveApplicationService.GetLeaveApplication(0);
                vm.LeaveCategories = leaveCategoryService.GetLeaveCategorySelectModels();
                vm.LeaveBalance = leaveApplicationService.GetLeaveBalance();
                return View("CreateOrEdit", vm);
            }
            else
            {
                TempData["successMessage"] = "Application Submitted Successfully";
            }
            return RedirectToAction("Index");
        }



        [SessionExpire]
        [HttpGet]
        public ActionResult ManagerLeaveApproval(int? Page_No, string searchText)
        {
            searchText = searchText == null ? "" : searchText;
            ViewBag.Title = "Manager Leave Approval";
            List<LeaveApplicationModel> leaveApplications = leaveApplicationService.GetManagerLeaveApprovals(searchText);
            int Size_Of_Page = 10;
            int No_Of_Page = (Page_No ?? 1);
            return View(leaveApplications.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        [SessionExpire]
        [HttpGet]
        public ActionResult ChangeMangerStatus(long leaveApplicationId, string Approved, string Denied, string comments)
        {
            string status = string.IsNullOrEmpty(Approved) ? Denied : Approved;
            string ip = Request.UserHostAddress;
            bool result = leaveApplicationService.ChangeMangerStatus(leaveApplicationId, status, comments, ip);
            return RedirectToAction("ManagerLeaveApproval");
        }


        [SessionExpire]
        [HttpGet]
        public ActionResult HRLeaveApproval(int? Page_No, string searchText)
        {
            searchText = searchText == null ? "" : searchText;
            ViewBag.Title = "HR Admin Leave Approval";
            List<LeaveApplicationModel> leaveApplications = leaveApplicationService.GetHRLeaveApprovals(searchText);
            int Size_Of_Page = 10;
            int No_Of_Page = (Page_No ?? 1);
            return View(leaveApplications.ToPagedList(No_Of_Page, Size_Of_Page));
        }



        [SessionExpire]
        [HttpGet]
        public ActionResult ChangeHRStatus(long leaveApplicationId, string Approved, string Denied, string comments)
        {
            string status = string.IsNullOrEmpty(Approved) ? Denied : Approved;
            string ip = Request.UserHostAddress;
            bool result = leaveApplicationService.ChangeHRStatus(leaveApplicationId, status, comments, ip);
            return RedirectToAction("HRLeaveApproval");
        }


        [SessionExpire]
        public ActionResult Delete(long id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LeaveApplicationModel leaveApplication = leaveApplicationService.GetLeaveApplication(id);
            if (leaveApplication == null)
            {
                return HttpNotFound();
            }
            return View(leaveApplication);
        }

        [SessionExpire]
        [HttpGet]
        public ActionResult LeaveBalance()
        {
            List<LeaveBalanceCustomModel> leaveBalances = leaveApplicationService.GetLeaveBalance();
            return View(leaveBalances);
        }

        [SessionExpire]
        [HttpGet]
        public async Task<ActionResult> TeamLeaveBalance(int selectedYear =0)
        {
            TeamLeaveBalanceCustomModel model = new TeamLeaveBalanceCustomModel();
            if(selectedYear == 0)
            {
                model.SelectedYear = DateTime.Now.Month >= 7 ? DateTime.Now.Year + 1 : DateTime.Now.Year;
            }
            else
            {
                model.SelectedYear = selectedYear;
            }

            model =await leaveApplicationService.GetTeamLeaveBalance(Convert.ToInt64(Session["Id"]), model.SelectedYear );        
            return View(model);
        }

        [SessionExpire]
        [HttpPost]
        public async Task<ActionResult> TeamLeaveBalance(TeamLeaveBalanceCustomModel model)
        {
            return RedirectToAction(nameof(TeamLeaveBalance), new { selectedYear = model.SelectedYear });
        }

        [SessionExpire]
        [HttpGet]
        public ActionResult EmployeeLeaveBalance(string employeeId)
        {
            employeeId = employeeId ?? string.Empty;
            EmployeeLeaveBalanceCustomModel cvm = new EmployeeLeaveBalanceCustomModel();
            cvm.LeaveBalanceCustomModels = leaveApplicationService.GetEmployeeLeaveBalance(employeeId, out string message);
            cvm.EmployeeCustomModel = leaveApplicationService.GetCustomEmployeeModel(employeeId);
            ViewBag.message = message;
            if (!string.IsNullOrEmpty(employeeId))
            {
                ViewBag.leaveHistory = GetLeaveHistory(employeeId);
            }
            return View(cvm);
        }


        #region Leave History by Manager search

        public string GetLeaveHistory(string employeeId)
        {
            string htmlStr = "";
            DataTable dt = new DataTable();
            dt = GetEmployeeHistoryByEmployeeId(employeeId);
            StringBuilder sb = new StringBuilder();
            if (dt.Rows.Count > 0)
            {
                //Table start.
                sb.Append("<table cellpadding='5' cellspacing='0' style='width:100%; border: 1px solid #ccc;font-size: 10pt;font-family:Arial'>");
                //Adding HeaderRow.
                sb.Append("<tr>");
                foreach (DataColumn column in dt.Columns)
                {
                    sb.Append("<th style='background-color: #009270; padding:5px; color:white; border: 1px;' align='center'>" + column.ColumnName + "</th>");
                }
                sb.Append("</tr>");

                //Adding DataRow.
                foreach (DataRow row in dt.Rows)
                {
                    sb.Append("<tr>");
                    foreach (DataColumn column in dt.Columns)
                    {
                        if (column.ColumnName == "Reason")
                        {
                            sb.Append("<td style='width:200px;border: 1px solid #ccc' align='left'>" + row[column.ColumnName].ToString() + "</td>");
                        }
                        else if (column.ColumnName == "Days")
                        {
                            sb.Append("<td style='width:40px;border: 1px solid #ccc' align='center'>" + row[column.ColumnName].ToString() + "</td>");
                        }
                        else

KGERP/Views/LeaveApplication/DeniedLeave.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<KGERP.Service.ServiceModel.LeaveApplicationModel>
@using PagedList;

<div class="container" style="padding-left:20px">
    <div class="row" style="padding-bottom:5px">
        <div class="panel-heading">
            <h4>
                <b>
                    @if (ViewBag.Title != null)
                    {
                        @ViewBag.Title
                    }
                </b>
            </h4>
        </div>
    </div>

    <div class="row">
        <table class="table table-striped table-condensed">
            <tr class="panel panel-info">
                <th>
                    @Html.DisplayNameFor(model => model.First().EmployeeId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().StartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().ApplicationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().LeaveDays)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().ManagerStatus)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().HrAdminStatus)
                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @("[" + @Html.DisplayFor(modelItem => item.Employee.EmployeeId) + "] " + @Html.DisplayFor(modelItem => item.Employee.Name))

                    </td>
                    <td>
                        @if (item.StartDate != null)
                        {
                            @item.StartDate.Value.ToString("dd MMM yy")
                        }

                    </td>
                    <td>

                        @if (item.EndDate != null)
                        {
                            @item.EndDate.Value.ToString("dd MMM yy")
                        }
                    </td>
                    <td>
                        @if (item.ApplicationDate != null)
                        {
                            @item.ApplicationDate.Value.ToString("dd MMM yy")
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LeaveDays)
                    </td>
                    <td>
                        @if (item.ManagerStatus != null)
                        {
                            <span style="width:65px" class="@((item.ManagerStatus=="Approved")?"btn btn-success btn-xs":"btn btn-danger btn-xs")">
                                @Html.DisplayFor(modelItem => item.ManagerStatus)
                            </span>
                        }


                    </td>
                    <td>
                        @if (item.HrAdminStatus != null)
                        {

                            <span style="width:65px" class="@((item.HrAdminStatus=="Approved")?"btn btn-success btn-xs":"btn btn-danger btn-xs")">
                                @Html.DisplayFor(modelItem => item.HrAdminStatus)
                            </span>
                        }
                    </td>

                </tr>
            }

        </table>
        @if (Model.PageCount > 1)
        {
            <span class="btn btn-success">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            </span>
            <span class="checkbox">
                @Html.PagedListPager(Model, Page_No => Url.Action("Index", "LeaveApplication",
                        new { Page_No, Sorting_Order = Request.QueryString["Search"] }))
            </span>
        }

    </div>

</div>
@section Scripts{

    <script type="text/javascript">
        function changeStatus(leaveapplicationId) {
            var status = $('#ddlStatus').val();
            $.ajax({
                url: '/LeaveApplication/ChangeStatus?leaveapplicationId=' + leaveapplicationId + '&status=' + status,
                type: 'GET',
                success: function (data) {
                    alert('Success');
                    window.location.href = data.Url;
                },
                error: function () {
                    alert("error");
                }
            });
        }
    </script>
}

KGERP/Views/LeaveApplication/EmployeeLeaveBalance.cshtml
@model KGERP.Data.CustomViewModel.EmployeeLeaveBalanceCustomModel
@{
    ViewBag.Title = "Employee Leave Balance";
}

<div class="row">
    @using (Html.BeginForm("EmployeeLeaveBalance", "LeaveApplication", FormMethod.Get))
    {
        <div class="col-md-6">
            @Html.Label("Employee Leave Balance", new { @style = "font-size:20px" })
        </div>
        <div class="col-md-6">
            <div class="col-md-10">@Html.TextBox("employeeId", null, new { @autocomplete = "off", @class = "form-control pull-left", @placeholder = "Search..." })</div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-success">Search&nbsp;<i class="fa fa-search"></i></button>
            </div>
        </div>
    }
    <div class="col-md-6">
        @if (!string.IsNullOrEmpty(ViewBag.message))
        {
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>
                    @ViewBag.message
                </strong>
            </div>
        }
    </div>
</div>

<hr style="border-color:red; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />

<div class="row">
    @if (Model.LeaveBalanceCustomModels.Any())
    {
        <div class="col-md-3">
            <div><b> Name:  @Model.EmployeeCustomModel.EmployeeName</div>
            <div> ID :  @Model.EmployeeCustomModel.EmployeeID</div>

        </div>

        <div class="col-md-9">
            <table class="table table-striped table-responsive">
                <thead>
                    <tr style="background-color:#4CAF50;color:#FFFFFF">
                        <th>Leave Type</th>
                        <th>Total Leave</th>
                        <th>Leave Availed</th>
                        <th>Leave Due</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.LeaveBalanceCustomModels)
                    {
                        <tr>
                            <td><span>@item.LeaveCategory</span></td>
                            <td><span class="badge" style="background-color:blue">@item.MaxDays</span></td>
                            <td><span class="badge" style="background-color:red">@item.LeaveAvailed</span></td>
                            <td><span class="badge" style="background-color:forestgreen">@(item.MaxDays - item.LeaveAvailed)</span></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }

</div>
<div>
    @if (ViewBag.leaveHistory != null)
    {
        @Html.Raw(ViewBag.leaveHistory)
    }
</div>

KGERP/Views/LeaveApplication/EmployeeLeaveBalanceByIdnDateRange.cshtml
@model KGERP.Data.CustomViewModel.EmployeeLeaveBalanceCustomModel
@{
    ViewBag.Title = "Employee Leave Balance";
}

<style type="text/css">

    /*Custom table CSS*/
    .text-on-pannel {
        background: #fff none repeat scroll 0 0;
        height: auto;
        margin-left: 20px;
        padding: 3px 5px;
        position: absolute;
        margin-top: -47px;
        border: 1px solid #337ab7;
        border-radius: 8px;
    }

    .panel {
        /* for text on pannel */
        margin-top: 27px !important;
    }

    .panel-body {
        padding-top: 30px !important;
    }

    .spacing-table {
        font-family: 'Helvetica', 'Arial', sans-serif;
        font-size: 12px;
        border-collapse: separate;
        border-spacing: 0 5px; /* this is the ultimate fix */
        width: 100%;
    }

        .spacing-table th {
            text-align: left;
            padding: 5px 5px;
        }

        .spacing-table td {
            border-width: 3px 0;
            /* border-color: darkred;
                border-style: solid;*/
            background-color: #f1f1f1;
            color: Black;
            padding: 5px 5px;
        }

            .spacing-table td:first-child {
                /*  border-left-width: 3px;*/
                border-radius: 5px 0 0 5px;
            }

            .spacing-table td:last-child {
                /*border-right-width: 3px;*/
                border-radius: 0 5px 5px 0;
            }

    .image {
        float: left;
        max-height: 50px;
        max-width: 50px;
        margin-right: 10px;
    }

    .name {
        margin: 0;
        padding: 0;
    }

    .username {
        display: block;
        font-weight: bold;
        margin-bottom: 1em;
    }

    .ui-autocomplete {
        max-height: 320px;
        overflow: auto;
    }

    .tdRightAlign {
        width: 10%;
        font-size: medium;
        text-align: right;
    }

    .tdCenterAlign {
        background-color: #E9EDBE;
        vertical-align: middle;
        text-align: center;
    }

    /*Red Horizontal Line*/
    .redHorizontalLine {
        border-color: red;
        padding: 0px;
        margin-top: 10px;
        margin-bottom: 20px;
        border-width: 2px;
    }
</style>

@using (Html.BeginForm("EmployeeLeaveBalanceByIdnDateRange", "LeaveApplication", FormMethod.Get))
{
    <div class="row">
        <table class="spacing-table">
            <tr>
                <td class="tdRightAlign">  @Html.Label("From Date", new { @style = "font-size:14px" })</td>
                <td style="background-color: #E9EDBE; vertical-align: middle;">
                    <input type="datetime" class="datepicker pull-left " name="StartDate" value="@ViewBag.FromDate" autocomplete="off">
                </td>
                <td class="tdRightAlign">   @Html.Label("To Date", new { @style = "font-size:14px" })</td>
                <td style="background-color: #E9EDBE; vertical-align: middle;">
                    <input type="datetime" class="datepicker pull-left " name="EndDate" value="@ViewBag.ToDate" autocomplete="off">
                </td>
                <td class="tdRightAlign">   @Html.Label("Employee Id", new { @style = "font-size:14px" })</td>
                <td style="background-color: #E9EDBE; vertical-align: middle;">
                    @Html.TextBox("employeeId", null, new { @autocomplete = "off", @class = "form-control pull-left", @placeholder = "Search..." })
                </td>
            </tr>
        </table>
    </div>

    <hr style="border-color:red; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />
    <div class="row">
        <div class="col-md-6">
            @Html.Label("Employee Leave Balance", new { @style = "font-size:20px" })

        </div>

        <div class="col-md-6">
            <div class="col-md-12 pull-right">
                <button type="submit" class="btn btn-success">Search&nbsp;<i class="fa fa-search"></i></button>
            </div>
        </div>
    </div>
}


<hr style="border-color:red; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />
<div class="row">
    @if (!string.IsNullOrEmpty(ViewBag.message))
    {
        <div class="alert alert-danger alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>
                @ViewBag.message
            </strong>
        </div>
    }
</div>
<div class="row">
    @if (Model.LeaveBalanceCustomModels.Any())
    {<table class="table table-bordered" style="background-color:#f1f1f1;">
            <tr>
                <td align="right">Employee</td>
                <td>@Model.EmployeeCustomModel.EmployeeName</td>             
                <td  align="right">Employee ID</td>
                <td>@Model.EmployeeCustomModel.EmployeeID</td>
            </tr>
        </table>
        <table class="table table-striped table-responsive">
            <thead>
                <tr style="background-color:#4CAF50;color:#FFFFFF">
                    <th>Leave Type</th>
                    <th>Total Leave</th>
                    <th>Leave Availed</th>
                    <th>Leave Due</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.LeaveBalanceCustomModels)
                {
                    <tr>
                        <td><span>@item.LeaveCategory</span></td>
                        <td><span class="badge" style="background-color:blue">@item.MaxDays</span></td>
                        <td><span class="badge" style="background-color:red">@item.LeaveAvailed</span></td>
                        <td><span class="badge" style="background-color:forestgreen">@(item.MaxDays - item.LeaveAvailed)</span></td>
                    </tr>
                }

            </tbody>
        </table>
    }
</div>

KGERP/Views/LeaveApplication/HRLeaveApproval.cshtml
@using PagedList.Mvc;
@using KGERP.Utility
@model PagedList.IPagedList<KGERP.Service.ServiceModel.LeaveApplicationModel>
@using PagedList;

<link href="~/Content/CustomCss/search-form.css" rel="stylesheet" />
<div class="row">
    @using (Html.BeginForm("HRLeaveApproval", "LeaveApplication", FormMethod.Get, new { @class = "example" }))
    {
        <div class="col-md-8">
            <h4>
                <b>
                    @if (ViewBag.Title != null)
                    {
                        @ViewBag.Title
                    }
                </b>
            </h4>
        </div>
        <div class="col-md-4">
            @Html.Editor("searchText", new { htmlAttributes = new { @autocomplete = "off", value = "", @placeholder = "Search..", @style = "width:75%" } })
            <button type="submit"><i class="fa fa-search "></i></button>
        </div>
    }
</div>

<div class="row">
    <hr style="border-color:red; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    <table class="table table-striped table-responsive">
        <tr style="background-color:#4CAF50;color:#FFFFFF">
            <th>
                SL
            </th>
            <th>
                EmployeeID
            </th>
            <th>
                Name
            </th>
            <th>
                Department
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().LeaveCategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Reason)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().ApplicationDate)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().EndDate)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.First().LeaveDays)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().ManagerStatus)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().HrAdminStatus)
            </th>

        </tr>

        @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td>
                    @((item.Index + 1) + (Model.PageNumber - 1) * Model.PageSize)

                </td>
                <td>
                    <span title="@("Designation : "+item.Data.DesignationName)">@item.Data.EmployeeId</span>
                </td>
                <td>
                    <span title="@("Designation : "+item.Data.DesignationName)">@item.Data.EmployeeName</span>
                    @*@item.Data.EmployeeName*@
                </td>
                <td>
                    @item.Data.DepartmentName
                </td>
                <td nowrap>
                    @item.Data.LeaveName
                </td>
                <td>
                    @item.Data.Reason
                </td>
                <td nowrap>
                    @if (item.Data.ApplicationDate.HasValue)
                    {
                        @item.Data.ApplicationDate.Value.ToString("dd-MMM-yyyy")
                    }
                </td>
                <td nowrap>
                    @if (item.Data.StartDate != null)
                    {
                        @item.Data.StartDate.Value.ToString("dd-MMM-yyyy")
                    }
                </td>
                <td nowrap>
                    @if (item.Data.EndDate.HasValue)
                    {
                        @item.Data.EndDate.Value.ToString("dd-MMM-yyyy")
                    }
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Data.LeaveDays)
                </td>
                <td>
                    <span style="width:65px" class="@(item.Data.ManagerStatus=="Pending"?"btn btn-warning btn-xs":(item.Data.ManagerStatus=="Approved"?"btn btn-success btn-xs":"btn btn-danger btn-xs")) btn btn-success btn-xs" title="@item.Data.ManagerComment">
                        @Html.DisplayFor(modelItem => item.Data.ManagerStatus)
                    </span>
                </td>

                <td>

                    @if (item.Data.HrAdminStatus == "Pending")
                    {
                        using (Html.BeginForm("ChangeHRStatus", "LeaveApplication", FormMethod.Get, new { @novalidate = "novalidate" }))
                        {<button type="submit" name="Approved" value="Approved" class="btn btn-success btn-xs" title="Approve"><i class="fa fa-check" aria-hidden="true"></i></button>
                            <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#hrModal" title="Denied"><i class="fa fa-check" aria-hidden="true"></i></button>

                            <!-- Modal -->
                            <div class="modal" id="hrModal" role="dialog">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">HR Admin Comments</h4>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="leaveApplicationId" value="@item.Data.LeaveApplicationId" />
                                            <input type="hidden" name="status" value="Denied" />
                                            <input type="text" name="comments" class="form-control" min="5" required />
                                        </div>
                                        <div class="modal-footer">
                                            <input type="submit" name="Denied" value="Denied" class="btn btn-danger btn-xs" />
                                            <button type="button" class="btn btn-warning btn-xs" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }

                    else
                    {
                        if (!string.IsNullOrEmpty(item.Data.HrAdminStatus))
                        {
                            <span style="width:65px" class="@(item.Data.HrAdminStatus=="Approved"?"btn btn-success btn-xs":(item.Data.ManagerStatus=="Denied"?"btn btn-danger btn-xs":"")) btn btn-success btn-xs" title="@item.Data.HrAdminComment">
                                @Html.DisplayFor(modelItem => item.Data.HrAdminStatus)
                            </span>
                        }

                    }

                </td>
            </tr>
        }

    </table>
    @if (Model.PageCount > 1)
    {
        <span class="btn btn-success">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        </span>
        <span class="checkbox">
            @Html.PagedListPager(Model, Page_No => Url.Action("HRLeaveApproval", "LeaveApplication", new { Page_No, Sorting_Order = Request.QueryString["Search"], SearchText = Request.QueryString["searchText"] }))
        </span>
    }

</div>


@section Scripts{

    <script type="text/javascript">

        $("#hrApprove").click(function () {
            if ($('#hrApprove').attr('id') == 'hrApprove') {
                $("#status").val("Approved")
            }
        })

        $("#hrDenied").click(function () {
            if ($('#hrDenied').attr('id') == 'hrDenied') {
                $("#status").val("Denied")
            }
        })


    </script>

}

KGERP/Views/LeaveApplication/ProcessLeave.cshtml
@{
    ViewBag.Title = "ProcessLeave";
}

<h3 style="color:green">
    @if(ViewBag.message != null)
    {
        @ViewBag.message
    }
</h3>