KGERP/Controllers/DamageController.cs
using System;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using System.Threading.Tasks;
using System.Web.Mvc;
using KGERP.Service.Implementation.Procurement;
using KGERP.Service.Implementation.Configuration;
using System.Linq;

namespace KGERP.Controllers
{
    [SessionExpire]
    public class DamageController : Controller
    {
        private readonly IDamageService _service;
        private readonly  ProcurementService procurementService;
        private readonly  ConfigurationService configurationService;
        private readonly IProductService productService;
        private readonly IStockInfoService _stockInfoService;
        public DamageController(ConfigurationService configurationService, IDamageService service, IStockInfoService stockInfoService, ProcurementService procurementService,  IProductService productService)
        {
            _service = service;
            this.procurementService = procurementService;
            this.configurationService = configurationService;
            this.productService = productService;
            _stockInfoService = stockInfoService;


        }

        #region 0. Customer Damage

        #region 0.1  Customer Entry Circle
        
        [HttpGet]
        public async Task<ActionResult> DamageMasterSlaveCustomer(int companyId = 0, int damageMasterId = 0)
        {
            DamageMasterModel demageMasterModel = new DamageMasterModel();

            if (damageMasterId == 0)
            {
                demageMasterModel.CompanyFK = companyId;
                demageMasterModel.StatusId = (int)EnumDamageStatus.Draft;
            }
            else
            {
                demageMasterModel = await _service.GetDamageMasterDetailCustomer(companyId, damageMasterId);

            }
            demageMasterModel.ZoneList = new SelectList(procurementService.ZonesDropDownList(companyId), "Value", "Text");
            demageMasterModel.DamageTypeList = new SelectList(configurationService.DamageTypeDropDownList(companyId), "Value", "Text");

            return View(demageMasterModel);
        }

        [HttpPost]
        public async Task<ActionResult> DamageMasterSlaveCustomer(DamageMasterModel demageMasterModel)
        {

            if (demageMasterModel.ActionEum == ActionEnum.Add)
            {
                if (demageMasterModel.DamageMasterId == 0)
                {
                    demageMasterModel.DamageMasterId = await _service.DamageMasterAddCustomer(demageMasterModel);

                }
                await _service.DamageDetailAdd(demageMasterModel);
            }
            else if (demageMasterModel.ActionEum == ActionEnum.Edit)
            {
                await _service.DamageDetailEdit(demageMasterModel);
            }
            return RedirectToAction(nameof(DamageMasterSlaveCustomer), new { companyId = demageMasterModel.CompanyFK, damageMasterId = demageMasterModel.DamageMasterId });
        }

        [HttpGet]
        public async Task<ActionResult> DamageMasterListCustomer(int companyId, DateTime? fromDate, DateTime? toDate, int? vStatus)
        {
            if (!fromDate.HasValue) fromDate = DateTime.Now.AddMonths(-2);
            if (!toDate.HasValue) toDate = DateTime.Now;

            DamageMasterModel damageMasterModel = new DamageMasterModel();
            damageMasterModel = await _service.GetDamageMasterListCustomer(companyId, fromDate, toDate, vStatus);
            damageMasterModel.UserDataAccessModel = await configurationService.GetUserDataAccessModelByEmployeeId();

            damageMasterModel.StrFromDate = fromDate.Value.ToString("yyyy-MM-dd");
            damageMasterModel.StrToDate = toDate.Value.ToString("yyyy-MM-dd");
            if (vStatus == null)
            {
                vStatus = -1;
            }
            damageMasterModel.StatusId = (EnumDamageStatus)vStatus;
            damageMasterModel.ZoneList = new SelectList(procurementService.ZonesDropDownList(companyId), "Value", "Text");

            return View(damageMasterModel);
        }

        [HttpPost]
        public ActionResult DamageOrderSearchCustomer(DamageMasterModel damageMasterModel)
        {
            if (damageMasterModel.CompanyId > 0)
            {
                Session["CompanyId"] = damageMasterModel.CompanyId;
            }

            damageMasterModel.FromDate = Convert.ToDateTime(damageMasterModel.StrFromDate);
            damageMasterModel.ToDate = Convert.ToDateTime(damageMasterModel.StrToDate);
            return RedirectToAction(nameof(DamageMasterListCustomer), new { companyId = damageMasterModel.CompanyId, fromDate = damageMasterModel.FromDate, toDate = damageMasterModel.ToDate, vStatus = (int)damageMasterModel.StatusId });

        }

        [HttpPost]
        public async Task<ActionResult> SubmitDamageMasterCustomer(DamageMasterModel demageMasterModel)
        
        
        {
            demageMasterModel.DamageMasterId = await _service.SubmitDamageMaster(demageMasterModel.DamageMasterId);
            return RedirectToAction(nameof(DamageMasterSlaveCustomer), new { companyId = demageMasterModel.CompanyFK });
        }


        [HttpPost]
        public async Task<ActionResult> DamageMasterEditCustomer(DamageMasterModel model)
        {
            if (model.ActionEum == ActionEnum.Edit)
            {
                await _service.DamageMasterEdit(model);
            }
            return RedirectToAction(nameof(DamageMasterListCustomer), new { companyId = model.CompanyFK });
        }

        [HttpPost]
        public async Task<ActionResult> DeleteDamageDetailByIdCustomer(DamageMasterModel demageMasterModel)
        {
            if (demageMasterModel.ActionEum == ActionEnum.Delete)
            {
                demageMasterModel.DetailModel.DamageDetailId = await _service.DamageDetailDelete(demageMasterModel.DetailModel.DamageDetailId);
            }
            return RedirectToAction(nameof(DamageMasterSlaveCustomer), new { companyId = demageMasterModel.CompanyFK, damageMasterId = demageMasterModel.DamageMasterId });
        }

        [HttpPost]
        public async Task<ActionResult> DeleteDamageMasterByIdCustomer(DamageMasterModel demageMasterModel)
        {
            if (demageMasterModel.ActionEum == ActionEnum.Delete)
            {
                demageMasterModel.DamageMasterId = await _service.DamageMasterDelete(demageMasterModel.DamageMasterId);
            }
            return RedirectToAction(nameof(DamageMasterListCustomer), new { companyId = demageMasterModel.CompanyFK });
        }
        #endregion

        #region 0.2  Customer receive
        [HttpGet]
        public async Task<ActionResult> CustomerDamageReceivedSlave(int companyId = 0, int damageMasterId = 0)
        {
            DamageMasterModel damageMasterModel = new DamageMasterModel();

            if (damageMasterId > 0)
            {
                damageMasterModel = await _service.GetDamageMasterDetailCustomer(companyId, damageMasterId);
                damageMasterModel.DetailDataList = damageMasterModel.DetailList.ToList();
            }

            return View(damageMasterModel);
        }

        [HttpPost]
        public async Task<ActionResult> CustomerDamageReceivedSlave(DamageMasterModel damageMasterModel)
        {
            var resutl = await _service.DealerDamageReceived(damageMasterModel);
            return RedirectToAction(nameof(CustomerDamageReceivedList), new { companyId = damageMasterModel.CompanyFK });
        }


        [HttpGet]
        public async Task<ActionResult> CustomerDamageReceivedList(int companyId, DateTime? fromDate, DateTime? toDate, int? vStatus)
        {
            if (!fromDate.HasValue) fromDate = DateTime.Now.AddMonths(-2);
            if (!toDate.HasValue) toDate = DateTime.Now;

            DamageMasterModel damageMasterModel = new DamageMasterModel();
            damageMasterModel = await _service.GetCustomerDamageMasterReceivedList(companyId, fromDate, toDate, vStatus);

            damageMasterModel.StrFromDate = fromDate.Value.ToString("yyyy-MM-dd");
            damageMasterModel.StrToDate = toDate.Value.ToString("yyyy-MM-dd");
            if (vStatus == null)
            {
                vStatus = -1;
            }
            damageMasterModel.StatusId = (EnumDamageStatus)vStatus;

            return View(damageMasterModel);
        }

        [HttpPost]
        public ActionResult CustomerDamageMasterReceivedSearch(DamageMasterModel damageMasterModel)
        {
            if (damageMasterModel.CompanyId > 0)
            {
                Session["CompanyId"] = damageMasterModel.CompanyId;
            }

            damageMasterModel.FromDate = Convert.ToDateTime(damageMasterModel.StrFromDate);
            damageMasterModel.ToDate = Convert.ToDateTime(damageMasterModel.StrToDate);
            return RedirectToAction(nameof(CustomerDamageReceivedList), new { companyId = damageMasterModel.CompanyId, fromDate = damageMasterModel.FromDate, toDate = damageMasterModel.ToDate, vStatus = (int)damageMasterModel.StatusId });

        }
        #endregion

        #region 0.3 SR Damage Entry
        [HttpGet]
        public async Task<ActionResult> SRDamageMasterSlaveCustomer(int companyId = 0, int damageMasterId = 0)
        {
            DamageMasterModel demageMasterModel = new DamageMasterModel();

            if (damageMasterId == 0)
            {
                demageMasterModel.CompanyFK = companyId;
                demageMasterModel.StatusId = (int)EnumDamageStatus.Draft;
            }
            else
            {
                demageMasterModel = await _service.GetDamageMasterDetailCustomer(companyId, damageMasterId);

            }
            //demageMasterModel.ZoneList = new SelectList(procurementService.ZonesDropDownList(companyId), "Value", "Text");
            demageMasterModel.DamageTypeList = new SelectList(configurationService.DamageTypeDropDownList(companyId), "Value", "Text");

KGERP/Views/Damage/CustomerDamageReceivedList.cshtml
 @model KGERP.Service.ServiceModel.DamageMasterModel
@using KGERP.Utility;

@{
    ViewData["Title"] = "Dealer Damage Received List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int sl = 0;
}

<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>

<section class="content-header">
    <h1>
        <span>
            Customer to Dealer Damage Receive List
        </span>

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        @*<li class="active">
            <a href="~/Procurement/DealerSalesOrderSlave?companyId=@Model.CompanyFK&orderMasterId=0" class="btn btn-primary pull-right">
                <span class="fs fs-plus"></span> New Sales Invoice
            </a>
        </li>*@
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-danger">
                    <div class="box-body">
                        @using (Html.BeginForm("CustomerDamageMasterReceivedSearch", "Damage", FormMethod.Post, new { id = "dealerReceivedListFormId", @class = "formValidator" }))
                        {
                            @Html.HiddenFor(model => model.CompanyId, new { id = "CompanyId" })

                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.Label("Status:", htmlAttributes: new { @class = "control-label" })
                                        <br />
                                        @Html.DropDownListFor(model => model.StatusId, Model.EnumDamageStatusList as SelectList, "==Select Status==", new { id = "ddlStatusEnumFK", @class = "form-control ddlReset searchingDropdown", style = "width:100%", required = "required" })
                                        @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.Label("From Date:", htmlAttributes: new { @class = "control-label" })
                                        <br />
                                        @Html.EditorFor(model => model.StrFromDate, new { htmlAttributes = new { @class = "datepicker", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.StrFromDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.Label("To Date:", htmlAttributes: new { @class = "control-label" })
                                        <br />
                                        @Html.EditorFor(model => model.StrToDate, new { htmlAttributes = new { @class = "datepicker", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.StrToDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="col-md-3" style="padding: 0px 2px 0px 8px;">
                                    <div class="form-group">
                                        <label>&nbsp;</label>
                                        <button type="submit" id="btnSave" class="btn btn-primary btn-block">Show</button>
                                    </div>
                                </div>
                            </div>
                        }

                        <hr />

                        <div class="table-responsive">
                            <table id="KgErpDataTable" class="table table-striped" style="width:100%; background-color:#ddd;">
                                <thead>
                                    <tr>
                                        <th>SL</th>
                                        <th>Damage No</th>
                                        <th>Date</th>
                                        <th>From Customer</th>
                                        <th>To Dealer</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                        <th>Change Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.DataList)
                                    {
                                        #region Link Title

                                        string statusTitle = "";

                                        if (item.StatusId != EnumDamageStatus.Received)
                                        { statusTitle = "Receive"; }

                                        if (item.StatusId == EnumDamageStatus.Received)
                                        { statusTitle = "Undo Receive"; }

                                        #endregion

                                        <tr>
                                            <th>@(++sl)</th> 
                                            <th>@item.DamageNo</th>
                                            <td>@item.OperationDate.ToString("dd-MM-yyyy")</td>
                                            <td>@item.CustomerName</td>
                                            <td>@item.DealerName</td>
                                            <td>@item.StatusName</td>
                                            <td>
                                                @if (item.StatusId == EnumDamageStatus.Received || item.StatusId == EnumDamageStatus.Submitted)
                                                {
                                                    <a href="~/Damage/CustomerDamageReceivedSlave?companyId=@item.CompanyFK&damageMasterId=@item.DamageMasterId" target="_blank" title="Details"><i class="glyphicon glyphicon-new-window"></i></a>
                                                }
                                            </td>
                                            <td>
                                                @if (item.StatusId == EnumDamageStatus.Received)
                                                {


                                                    <span class="border:1px solid;border-color:#006400;"><i style="color:#006400;">Received</i></span>
                                                }
                                                else
                                                {
                                                    <a href="~/Damage/CustomerDamageReceivedSlave?companyId=@item.CompanyFK&damageMasterId=@item.DamageMasterId" target="_blank" title="Details">Receive</a>

                                                }

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@Scripts.Render("~/bundles/jqueryui")
@Styles.Render("~/Content/cssjqryUi")

@section scripts {

    <script type="text/javascript">

        $('.datepicker').datepicker({
            dateFormat: "dd/mm/yy",
            showOn: 'both',
            buttonText: "<i class='fa fa-calendar'></i>",
            changeMonth: true,
            changeYear: true,
            yearRange: "2001:+50"
        });

        function resetForm() {

                $('#dealerReceivedListFormId')[0].reset();
                $('#SOEditActionId').val(1);
        }

        
        function DateCustom(orderDate) {

            var dateString = orderDate.substr(6);
            var currentTime = new Date(parseInt(dateString));
            var month = currentTime.getMonth() + 1;
            if (month < 10) {
                month = "0" + month;
            }

            var day = currentTime.getDate();
            var year = currentTime.getFullYear();
            var date = year + "-" + month + "-" + day;
            return date;
        }

    </script>
}

KGERP/Views/Damage/DealerToFacDamageReceivedList.cshtml
@model KGERP.Service.ServiceModel.DamageMasterModel
@using KGERP.Utility;

@{
    ViewData["Title"] = "Dealer Damage Received List";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int sl = 0;
}

<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>

<section class="content-header">
    <h1>
        <span>
            Dealer to Factory Damage Receive List
        </span>

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">
            @*<a href="~/Procurement/DealerSalesOrderSlave?companyId=@Model.CompanyFK&orderMasterId=0" class="btn btn-primary pull-right">
                <span class="fs fs-plus"></span> New Sales Invoice
            </a>*@
        </li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-danger">
                    <div class="box-body">
                        @using (Html.BeginForm("DealerToFacDamageMasterReceivedSearch", "Damage", FormMethod.Post, new { id = "dealerReceivedListFormId", @class = "formValidator" }))
                        {
                            @Html.HiddenFor(model => model.CompanyId, new { id = "CompanyId" })

                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.Label("Status:", htmlAttributes: new { @class = "control-label" })
                                        <br />
                                        @Html.DropDownListFor(model => model.StatusId, Model.EnumDamageStatusList as SelectList, "==Select Status==", new { id = "ddlStatusEnumFK", @class = "form-control ddlReset searchingDropdown", style = "width:100%", required = "required" })
                                        @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.Label("From Date:", htmlAttributes: new { @class = "control-label" })
                                        <br />
                                        @Html.EditorFor(model => model.StrFromDate, new { htmlAttributes = new { @class = "datepicker", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.StrFromDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.Label("To Date:", htmlAttributes: new { @class = "control-label" })
                                        <br />
                                        @Html.EditorFor(model => model.StrToDate, new { htmlAttributes = new { @class = "datepicker", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.StrToDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="col-md-3" style="padding: 0px 2px 0px 8px;">
                                    <div class="form-group">
                                        <label>&nbsp;</label>
                                        <button type="submit" id="btnSave" class="btn btn-primary btn-block">Show</button>
                                    </div>
                                </div>
                            </div>
                        }

                        <hr />

                        <div class="table-responsive">
                            <table id="KgErpDataTable" class="table table-striped" style="width:100%; background-color:#ddd;">
                                <thead>
                                    <tr>
                                        <th>SL</th> 
                                        <th>Damage No</th>
                                        <th>Date</th>
                                        <th>From Dealer</th>
                                        <th>To Store House</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                        <th>Change Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.DataList)
                                    {
                                        #region Link Title

                                        string statusTitle = "";

                                        if (item.StatusId != EnumDamageStatus.Received)
                                        { statusTitle = "Receive"; }

                                        if (item.StatusId == EnumDamageStatus.Received)
                                        { statusTitle = "Undo Receive"; }

                                        #endregion

                                        <tr>
                                            <th>@(++sl)</th> 
                                            <th>@(item.DamageNo)</th>
                                            <td>@item.OperationDate.ToString("dd-MM-yyyy")</td>
                                            <td>@item.DealerName</td>
                                            <td>@item.StockInfoName</td>
                                            <td>@item.StatusName</td>
                                            <td>
                                                @if (item.StatusId == EnumDamageStatus.Received || item.StatusId == EnumDamageStatus.Submitted)
                                                {
                                                    <a href="~/Damage/DealerToFacDamageReceivedSlave?companyId=@item.CompanyFK&damageMasterId=@item.DamageMasterId" target="_blank" title="Details"><i class="glyphicon glyphicon-new-window"></i></a>
                                                }
                                            </td>
                                            <td>
                                                @if (item.StatusId == EnumDamageStatus.Received)
                                                {


                                                    <span class="border:1px solid;border-color:#006400;"><i style="color:#006400;">Received</i></span>
                                                }
                                                else
                                                {
                                                    <a href="~/Damage/DealerToFacDamageReceivedSlave?companyId=@item.CompanyFK&damageMasterId=@item.DamageMasterId" target="_blank" title="Details">Receive</a>

                                                }

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@Scripts.Render("~/bundles/jqueryui")
@Styles.Render("~/Content/cssjqryUi")

@section scripts {

    <script type="text/javascript">

        $('.datepicker').datepicker({
            dateFormat: "dd/mm/yy",
            showOn: 'both',
            buttonText: "<i class='fa fa-calendar'></i>",
            changeMonth: true,
            changeYear: true,
            yearRange: "2001:+50"
        });

        function resetForm() {

                $('#dealerReceivedListFormId')[0].reset();
                $('#SOEditActionId').val(1);
        }

        
        function DateCustom(orderDate) {

            var dateString = orderDate.substr(6);
            var currentTime = new Date(parseInt(dateString));
            var month = currentTime.getMonth() + 1;
            if (month < 10) {
                month = "0" + month;
            }

            var day = currentTime.getDate();
            var year = currentTime.getFullYear();
            var date = year + "-" + month + "-" + day;
            return date;
        }

    </script>
}